steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/my-frontend-service'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_BASE_URL=${_NEXT_PUBLIC_API_BASE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}'
      - '.'
    dir: 'everlasting-hills-church'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/my-frontend-service']

  - name: 'gcr.io/google-cloud-sdk/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'my-frontend-service'
      - '--image=europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/my-frontend-service'
      - '--region=europe-west1'
      - '--port=3000'
      - '--allow-unauthenticated'
      - '--set-env-vars=NEXT_PUBLIC_API_BASE_URL=${_NEXT_PUBLIC_API_BASE_URL},DEFAULT_TENANT_ID=${_DEFAULT_TENANT_ID}'

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/my-frontend-service'